apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: anishka012/hello_app:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu : "0.2"
        ports:
        - containerPort: 80
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 80
        #   periodSeconds: 30
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 80
        #   periodSeconds: 10
        #   timeoutSeconds: 3
        readinessProbe:
          httpGet:
            port: 80
            path: /actuator/health/readiness
          initialDelaySeconds: 300
          periodSeconds: 30
        livenessProbe:
          httpGet:
            port: 80
            path: /actuator/health/liveness
          initialDelaySeconds: 300
          periodSeconds: 10
      # tolerations:
      # - key: "example-key"
      #   operator: "Exists"
      #   effect: "NoSchedule"
