name: "01-EKS"
on:
    push:
        branches:
            - feature-branch

jobs:
  Plan:
    uses: anishkasaxena/DevOps_project/.github/workflows/tf_plan.yaml@feature-branch
    
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Apply:
    needs: Plan
    uses: anishkasaxena/DevOps_project/.github/workflows/tf_apply.yaml@feature-branch
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}



